### PR TITLE
Codebase refactor.

### PR DESCRIPTION
**Pull request by janaSunrise**
This PR is aimed towards cleaning up the whole codebase. Following changes are to be done:
- [x] Sorting imports and code.
- [ ] Splitting into files
- [x] Split components into meaningful parts
- [ ] Create reusable components and hooks
- [ ] Have one component per file
- [x] Add dynamic imports
- [x] Split `utils` into `utils` and `lib`
- [ ] Optimize bundle and CSS.
- [ ] Adding validation for API and Frontend.
- [ ] Fixing memory issues and leaks.
- [ ] Removing redundant code, dependencies and cleaning it up.
- [ ] Making the code performant
- [ ] Fix bugs and errors (If any)
- [ ] Convert SSR into SSG/ISG if possible, and add speed-ups.

### CODE REVIEW

**Comment by max-programming** [comment]
image


@janaSunrise this is the error

**Comment by janaSunrise** [comment]
Thank you, I'll push a fix for that.

Also, is it possible for this page refactor (and are you good with it?

Maybe implement a landing page, and split the pages further.
- `/` will hold the landing page
- `/paste` will have the paste editor (with public pastes, as we still do)
- `/public-pastes` with all the public pastes (maybe infinite scrolling for optimizations?)

This would enable to have a beautiful initial page for people to view, and they can use paste (without authentication, or with it, as the features support both). A public pastes page would be great, alongside the other features we have planned, and it could make searching for useful snippets easier (as we implement full-text search, tags for pastes and the feed for sharing your pastes next too.)

**Comment by max-programming** [comment]
> Thank you, I'll push a fix for that.
> 
> Also, is it possible for this page refactor (and are you good with it?
> 
> Maybe implement a landing page, and split the pages further.
> 
> * `/` will hold the landing page
> * `/paste` will have the paste editor (with public pastes, as we still do)
> * `/public-pastes` with all the public pastes (maybe infinite scrolling for optimizations?)
> 
> This would enable to have a beautiful initial page for people to view, and they can use paste (without authentication, or with it, as the features support both). A public pastes page would be great, alongside the other features we have planned, and it could make searching for useful snippets easier (as we implement full-text search, tags for pastes and the feed for sharing your pastes next too.)

Yes! We can do that, for the landing page I think it's better to add the public pastes directly. Because every time a user visits the landing page they might not want to see the page. If an un-authenticated user views `/`, they might see a landing page and if they are authenticated they will see the public pastes. How is that idea?

**Comment by janaSunrise** [comment]
> > Thank you, I'll push a fix for that.
> > Also, is it possible for this page refactor (and are you good with it?
> > Maybe implement a landing page, and split the pages further.
> > 
> > * `/` will hold the landing page
> > * `/paste` will have the paste editor (with public pastes, as we still do)
> > * `/public-pastes` with all the public pastes (maybe infinite scrolling for optimizations?)
> > 
> > This would enable to have a beautiful initial page for people to view, and they can use paste (without authentication, or with it, as the features support both). A public pastes page would be great, alongside the other features we have planned, and it could make searching for useful snippets easier (as we implement full-text search, tags for pastes and the feed for sharing your pastes next too.)
> 
> Yes! We can do that, for the landing page I think it's better to add the public pastes directly. Because every time a user visits the landing page they might not want to see the page. If an un-authenticated user views `/`, they might see a landing page and if they are authenticated they will see the public pastes. How is that idea?

Yeah, that seems great! But, maybe would be better to keep `/` and `/public-pastes` separate? We can instead do this, `/` for landing page if unauthenticated, else a dashboard?

**Comment by max-programming** [comment]
> Yeah, that seems great! But, maybe would be better to keep `/` and `/public-pastes` separate? We can instead do this, `/` for landing page if unauthenticated, else a dashboard?

That's a better idea. If the user is not authenticated then they will stay on `/` else they will be redirected.
We can use `getServerSideProps` and [Clerk SSR](https://docs.clerk.dev/popular-guides/ssr-beta) for that

**Comment by janaSunrise** [comment]
Yes! Sounds perfect :)

**Pull request closed without merging**
